-- MySQL Script generated by MySQL Workbench
-- 11/11/15 15:09:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DankTank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DankTank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DankTank` DEFAULT CHARACTER SET utf8 ;
USE `DankTank` ;

-- -----------------------------------------------------
-- Table `DankTank`.`apartment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DankTank`.`apartment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DankTank`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DankTank`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `remember_token` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DankTank`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DankTank`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `postalCode` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `arrivalDate` DATETIME NOT NULL,
  `leavingDate` DATETIME NOT NULL,
  `amountOfGuests` INT NOT NULL,
  `amountOfChildren` INT NOT NULL,
  `apartment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_booking_apartment1_idx` (`apartment_id` ASC),
  CONSTRAINT `fk_booking_apartment1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `DankTank`.`apartment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
